"""Parameter grids, aggregation, tables, and figures for all revision studies."""

from __future__ import annotations

import csv
from dataclasses import replace
from pathlib import Path
from typing import Callable, Iterable, Sequence

import numpy as np

from .plotting import plot_bands, plot_lines, plot_tradeoff
from .simulator import (
    DEFAULT_CONFIG,
    SimulationConfig,
    TrialResult,
    controller_config,
    make_paths,
    simulate_trial,
)


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "results" / "revision_sim"
CONTROLLERS = ("PP", "APP", "RPP", "DWPP")
NOISE_LEVELS = (
    (0.0, 0.0),
    (0.01, 0.005),
    (0.02, 0.01),
    (0.05, 0.025),
    (0.10, 0.05),
)
SEEDS = tuple(range(20))


def _format_csv(value: object) -> object:
    if isinstance(value, (float, np.floating)):
        return f"{float(value):.9g}"
    return value


def write_table(rows: Sequence[dict[str, object]], csv_path: Path) -> None:
    if not rows:
        raise ValueError(f"Cannot write an empty table: {csv_path}")
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    fields = list(rows[0])
    with csv_path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: _format_csv(row[key]) for key in fields})
    write_latex(rows, csv_path.with_suffix(".tex"))


def _latex_escape(value: object) -> str:
    text = _format_csv(value)
    return str(text).replace("_", r"\_").replace("%", r"\%")


def write_latex(rows: Sequence[dict[str, object]], tex_path: Path) -> None:
    fields = list(rows[0])
    alignment = "l" + "r" * (len(fields) - 1)
    lines = [
        "% Auto-generated by scripts/revision/run_studies.py",
        rf"\begin{{tabular}}{{{alignment}}}",
        r"\toprule",
        " & ".join(_latex_escape(field) for field in fields) + r" \\",
        r"\midrule",
    ]
    lines.extend(" & ".join(_latex_escape(row[field]) for field in fields) + r" \\" for row in rows)
    lines.extend((r"\bottomrule", r"\end{tabular}", ""))
    tex_path.write_text("\n".join(lines), encoding="utf-8")


def _run(
    path: np.ndarray,
    path_name: str,
    config: SimulationConfig,
    *,
    sigma_xy: float = 0.0,
    sigma_yaw: float = 0.0,
    seed: int = 0,
) -> TrialResult:
    return simulate_trial(
        path,
        path_name,
        config,
        sigma_xy=sigma_xy,
        sigma_yaw=sigma_yaw,
        seed=seed,
    )


def run_smoke(output_root: Path = DEFAULT_OUTPUT_ROOT) -> dict[str, object]:
    paths = make_paths()
    rows: list[dict[str, object]] = []
    results: dict[tuple[str, str], TrialResult] = {}
    for path_name, path in paths.items():
        for controller in CONTROLLERS:
            result = _run(path, path_name, controller_config(controller))
            results[path_name, controller] = result
            rows.append(result.as_row())
    out = output_root / "smoke"
    write_table(rows, out / "smoke_table.csv")

    path_c = [results["PathC", name].mean_error for name in CONTROLLERS]
    ordering_pass = all(left > right for left, right in zip(path_c, path_c[1:]))
    zero_pass = all(results[path_name, "DWPP"].violation_ratio == 0.0 for path_name in paths)
    goal_pass = all(result.reached_goal for result in results.values())
    passed = ordering_pass and zero_pass and goal_pass
    ordering = {
        path_name: " > ".join(
            name for name, _ in sorted(
                ((controller, results[path_name, controller].mean_error) for controller in CONTROLLERS),
                key=lambda item: item[1],
                reverse=True,
            )
        )
        for path_name in paths
    }
    print(
        f"SMOKE {'PASS' if passed else 'FAIL'}: PathC={ordering['PathC']}; "
        f"DWPP zero violation={zero_pass}; all reached={goal_pass}"
    )
    if not passed:
        details = ", ".join(f"{name}={results['PathC', name].mean_error:.6f}" for name in CONTROLLERS)
        raise AssertionError(
            f"Smoke requirements failed ({details}; DWPP zero violation={zero_pass}; all reached={goal_pass})"
        )
    return {"passed": passed, "ordering": ordering, "rows": rows}


def _study_rows(
    values: Iterable[float],
    paths: dict[str, np.ndarray],
    arms: Sequence[str],
    config_builder: Callable[[str, float], SimulationConfig],
    parameter_name: str,
) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for path_name, path in paths.items():
        for value in values:
            for arm in arms:
                result = _run(path, path_name, config_builder(arm, float(value)))
                row = result.as_row()
                row = {"path": row.pop("path"), "arm": arm, parameter_name: float(value), **row}
                rows.append(row)
    return rows


def _filter(rows: Sequence[dict[str, object]], **conditions: object) -> list[dict[str, object]]:
    return [row for row in rows if all(row[key] == value for key, value in conditions.items())]


def run_app(output_root: Path = DEFAULT_OUTPUT_ROOT) -> dict[str, object]:
    values = np.round(np.linspace(0.6, 3.0, 13), 10)
    paths_all = make_paths()
    paths = {name: paths_all[name] for name in ("PathC", "PathA")}

    def build(arm: str, value: float) -> SimulationConfig:
        base = controller_config("APP")
        return replace(
            base,
            controller_name=arm,
            lookahead_time=value,
            use_dynamic_window=arm == "APP+DW",
            use_curvature_regulation=False,
        )

    rows = _study_rows(values, paths, ("APP", "APP+DW"), build, "lookahead_time")
    out = output_root / "app"
    write_table(rows, out / "app_table.csv")
    path_c_groups = []
    violation_groups = []
    for arm in ("APP", "APP+DW"):
        selected = _filter(rows, path="PathC", arm=arm)
        path_c_groups.append(
            (
                arm,
                [float(row["travel_time"]) for row in selected],
                [float(row["mean_error"]) for row in selected],
                [float(row["lookahead_time"]) for row in selected],
            )
        )
        violation_groups.append(
            (
                arm,
                [float(row["lookahead_time"]) for row in selected],
                [float(row["violation_ratio"]) for row in selected],
            )
        )
    plot_tradeoff(
        path_c_groups,
        out / "app_tradeoff",
        title="PathC: adaptive-lookahead trade-off",
        annotation_label=r"annotation: $l_t$",
    )
    plot_lines(
        violation_groups,
        out / "app_violation_vs_lookahead_time",
        xlabel=r"Lookahead time $l_t$ [s]",
        ylabel="Constraint violation ratio [%]",
        title="PathC: dynamic-constraint violations",
    )
    comparisons = []
    for path_name in paths:
        for value in values:
            plain = _filter(rows, path=path_name, arm="APP", lookahead_time=float(value))[0]
            dynamic = _filter(rows, path=path_name, arm="APP+DW", lookahead_time=float(value))[0]
            comparisons.append(float(dynamic["mean_error"]) - float(plain["mean_error"]))
    return {
        "rows": rows,
        "app_dw_exceeds_count": int(sum(delta > 1e-12 for delta in comparisons)),
        "max_app_dw_minus_app": max(comparisons),
    }


def run_rpp(output_root: Path = DEFAULT_OUTPUT_ROOT) -> dict[str, object]:
    values = np.round(np.linspace(0.3, 2.0, 10), 10)
    paths_all = make_paths()
    paths = {name: paths_all[name] for name in ("PathC", "PathA")}

    def build(arm: str, value: float) -> SimulationConfig:
        base = controller_config(arm)
        return replace(base, regulated_min_radius=value)

    rows = _study_rows(values, paths, ("RPP", "DWPP"), build, "regulated_min_radius")
    out = output_root / "rpp"
    write_table(rows, out / "rpp_table.csv")
    tradeoff_groups = []
    violation_groups = []
    for arm in ("RPP", "DWPP"):
        selected = _filter(rows, path="PathC", arm=arm)
        tradeoff_groups.append(
            (
                arm,
                [float(row["travel_time"]) for row in selected],
                [float(row["mean_error"]) for row in selected],
                [float(row["regulated_min_radius"]) for row in selected],
            )
        )
        violation_groups.append(
            (
                arm,
                [float(row["regulated_min_radius"]) for row in selected],
                [float(row["violation_ratio"]) for row in selected],
            )
        )
    plot_tradeoff(
        tradeoff_groups,
        out / "rpp_tradeoff",
        title="PathC: curvature-regulation trade-off",
        annotation_label=r"annotation: $R_{min}$",
    )
    plot_lines(
        violation_groups,
        out / "rpp_violation_vs_min_radius",
        xlabel=r"Minimum radius $R_{min}$ [m]",
        ylabel="Constraint violation ratio [%]",
        title="PathC: dynamic-constraint violations",
    )
    summary: dict[str, object] = {"rows": rows}
    for arm in ("RPP", "DWPP"):
        selected = _filter(rows, path="PathC", arm=arm)
        summary[f"{arm.lower()}_error_endpoints"] = (
            float(selected[0]["mean_error"]),
            float(selected[-1]["mean_error"]),
        )
        summary[f"{arm.lower()}_time_endpoints"] = (
            float(selected[0]["travel_time"]),
            float(selected[-1]["travel_time"]),
        )
    return summary


def _aggregate_trials(
    trials: Sequence[TrialResult],
    identifying: dict[str, object],
) -> dict[str, object]:
    row: dict[str, object] = {**identifying, "n": len(trials)}
    row["reached_goal_count"] = sum(trial.reached_goal for trial in trials)
    row["reached_goal_rate"] = 100.0 * float(row["reached_goal_count"]) / len(trials)
    for metric in ("travel_time", "mean_error", "max_error", "violation_ratio"):
        values = np.asarray([getattr(trial, metric) for trial in trials], dtype=float)
        row[f"{metric}_mean"] = float(np.mean(values))
        row[f"{metric}_std"] = float(np.std(values, ddof=1)) if len(values) > 1 else 0.0
    return row


def run_noise(output_root: Path = DEFAULT_OUTPUT_ROOT) -> dict[str, object]:
    path = make_paths()["PathC"]
    rows: list[dict[str, object]] = []
    for sigma_xy, sigma_yaw in NOISE_LEVELS:
        for controller in CONTROLLERS:
            trials = [
                _run(
                    path,
                    "PathC",
                    controller_config(controller),
                    sigma_xy=sigma_xy,
                    sigma_yaw=sigma_yaw,
                    seed=seed,
                )
                for seed in SEEDS
            ]
            rows.append(
                _aggregate_trials(
                    trials,
                    {"path": "PathC", "controller": controller, "sigma_xy": sigma_xy, "sigma_yaw": sigma_yaw},
                )
            )
    out = output_root / "noise"
    write_table(rows, out / "noise_table.csv")
    error_groups = []
    violation_groups = []
    for controller in CONTROLLERS:
        selected = _filter(rows, controller=controller)
        xs = [float(row["sigma_xy"]) for row in selected]
        error_groups.append(
            (
                controller,
                xs,
                [float(row["mean_error_mean"]) for row in selected],
                [float(row["mean_error_std"]) for row in selected],
            )
        )
        violation_groups.append(
            (
                controller,
                xs,
                [float(row["violation_ratio_mean"]) for row in selected],
                [float(row["violation_ratio_std"]) for row in selected],
            )
        )
    plot_bands(
        error_groups,
        out / "noise_mean_error",
        xlabel=r"Position-noise standard deviation $\sigma_{xy}$ [m]",
        ylabel="Mean tracking error [m]",
        title="PathC: localization-noise sensitivity",
    )
    plot_bands(
        violation_groups,
        out / "noise_violation_ratio",
        xlabel=r"Position-noise standard deviation $\sigma_{xy}$ [m]",
        ylabel="Constraint violation ratio [%]",
        title="PathC: violations under localization noise",
    )
    dwpp_zero = all(float(row["violation_ratio_mean"]) == 0.0 for row in _filter(rows, controller="DWPP"))
    if not dwpp_zero:
        raise AssertionError("DWPP produced a constraint violation in the noise study")
    return {"rows": rows, "dwpp_zero_violation": dwpp_zero}


def run_lookahead(output_root: Path = DEFAULT_OUTPUT_ROOT) -> dict[str, object]:
    path = make_paths()["PathC"]
    values = np.round(np.arange(0.3, 1.21, 0.1), 10)
    noise_levels = ((0.0, 0.0), (0.02, 0.01), (0.05, 0.025))
    rows: list[dict[str, object]] = []
    for sigma_xy, sigma_yaw in noise_levels:
        seeds = (0,) if sigma_xy == 0.0 else SEEDS
        for lookahead in values:
            config = replace(
                controller_config("DWPP"),
                use_velocity_scaled_lookahead=False,
                fixed_lookahead=float(lookahead),
            )
            trials = [
                _run(
                    path,
                    "PathC",
                    config,
                    sigma_xy=sigma_xy,
                    sigma_yaw=sigma_yaw,
                    seed=seed,
                )
                for seed in seeds
            ]
            rows.append(
                _aggregate_trials(
                    trials,
                    {"path": "PathC", "lookahead": float(lookahead), "sigma_xy": sigma_xy, "sigma_yaw": sigma_yaw},
                )
            )
    out = output_root / "lookahead"
    write_table(rows, out / "lookahead_table.csv")
    error_groups = []
    time_groups = []
    practical_bounds: dict[float, float] = {}
    summary_rows: list[dict[str, object]] = []
    for sigma_xy, _ in noise_levels:
        selected = _filter(rows, sigma_xy=sigma_xy)
        label = rf"$\sigma_{{xy}}={sigma_xy:g}$ m"
        xs = [float(row["lookahead"]) for row in selected]
        means = [float(row["mean_error_mean"]) for row in selected]
        stds = [float(row["mean_error_std"]) for row in selected]
        error_groups.append((label, xs, means, stds))
        time_groups.append((label, xs, [float(row["travel_time_mean"]) for row in selected], [float(row["travel_time_std"]) for row in selected]))
        completed = [
            (x, mean)
            for x, mean, row in zip(xs, means, selected, strict=True)
            if int(row["reached_goal_count"]) == int(row["n"])
        ]
        if not completed:
            raise RuntimeError(f"No lookahead completed every trial at sigma_xy={sigma_xy}")
        threshold = min(mean for _, mean in completed) * 1.10
        usable = [x for x, mean in completed if mean <= threshold]
        practical_bounds[sigma_xy] = min(usable)
        summary_rows.append(
            {
                "sigma_xy": sigma_xy,
                "practical_lower_bound": min(usable),
                "criterion": "100% goal; error <= 1.10 * successful minimum",
                "minimum_mean_error": min(mean for _, mean in completed),
            }
        )
    write_table(summary_rows, out / "lookahead_practical_bounds.csv")
    plot_bands(
        error_groups,
        out / "lookahead_mean_error",
        xlabel="Fixed lookahead distance L [m]",
        ylabel="Mean tracking error [m]",
        title="PathC: fixed-lookahead robustness",
    )
    plot_bands(
        time_groups,
        out / "lookahead_travel_time",
        xlabel="Fixed lookahead distance L [m]",
        ylabel="Travel time [s]",
        title="PathC: fixed-lookahead travel time",
    )
    return {"rows": rows, "practical_lower_bounds": practical_bounds}


def _match_time(
    path: np.ndarray,
    path_name: str,
    controller: str,
    target_time: float,
) -> TrialResult:
    low = 0.05
    high = DEFAULT_CONFIG.max_linear_velocity
    best: TrialResult | None = None
    for _ in range(28):
        value = (low + high) / 2.0
        config = replace(controller_config(controller), max_linear_velocity=value)
        result = _run(path, path_name, config)
        if best is None or abs(result.travel_time - target_time) < abs(best.travel_time - target_time):
            best = result
        relative_error = abs(result.travel_time - target_time) / target_time
        if relative_error <= 0.02:
            break
        if result.travel_time > target_time:
            low = value
        else:
            high = value
    assert best is not None
    if abs(best.travel_time - target_time) / target_time > 0.02:
        raise RuntimeError(
            f"Could not match {path_name}/{controller} to {target_time:.3f}s; best={best.travel_time:.3f}s"
        )
    return best


def run_isotime(output_root: Path = DEFAULT_OUTPUT_ROOT) -> dict[str, object]:
    rows: list[dict[str, object]] = []
    for path_name, path in make_paths().items():
        dwpp = _run(path, path_name, controller_config("DWPP"))
        for controller in ("PP", "APP"):
            result = _match_time(path, path_name, controller, dwpp.travel_time)
            row = result.as_row()
            rows.append(
                {
                    "path": path_name,
                    "controller": f"{controller}@matched",
                    "v_max": float(np.max(result.commands[:, 0])),
                    "travel_time": row["travel_time"],
                    "mean_error": row["mean_error"],
                    "max_error": row["max_error"],
                    "violation_ratio": row["violation_ratio"],
                }
            )
        rows.append(
            {
                "path": path_name,
                "controller": "DWPP",
                "v_max": DEFAULT_CONFIG.max_linear_velocity,
                "travel_time": dwpp.travel_time,
                "mean_error": dwpp.mean_error,
                "max_error": dwpp.max_error,
                "violation_ratio": dwpp.violation_ratio,
            }
        )
    out = output_root / "isotime"
    write_table(rows, out / "isotime_table.csv")
    return {"rows": rows}


STUDY_FUNCTIONS = {
    "smoke": run_smoke,
    "app": run_app,
    "rpp": run_rpp,
    "noise": run_noise,
    "lookahead": run_lookahead,
    "isotime": run_isotime,
}


def run_studies(study: str, output_root: Path = DEFAULT_OUTPUT_ROOT) -> dict[str, dict[str, object]]:
    names = tuple(STUDY_FUNCTIONS) if study == "all" else (study,)
    summaries: dict[str, dict[str, object]] = {}
    for index, name in enumerate(names, start=1):
        print(f"[{index}/{len(names)}] Running {name} study")
        summaries[name] = STUDY_FUNCTIONS[name](output_root)
        print(f"[{index}/{len(names)}] Completed {name} study")
    return summaries
