"""Parameter grids, aggregation, tables, and figures for all revision studies."""

from __future__ import annotations

import csv
from dataclasses import replace
from pathlib import Path
from typing import Callable, Iterable, Sequence

import numpy as np

from .plotting import (
    COLORS,
    plot_bands,
    plot_lines,
    plot_lookahead_tradeoff,
    plot_trajectories,
    plot_velocity_profiles,
    save_trajectory_legend,
)
from .simulator import (
    DEFAULT_CONFIG,
    SimulationConfig,
    TrialResult,
    controller_config,
    make_paths,
    simulate_trial,
)


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "results" / "revision_sim"
CONTROLLERS = ("PP", "APP", "RPP", "DWPP")
# sigma_yaw = 0.65 * sigma_xy, the AMCL correction-jump ratio measured on the
# exp1 real-robot logs (scripts/estimate_amcl_noise.py in the manuscript repo).
NOISE_LEVELS = (
    (0.0, 0.0),
    (0.01, 0.0065),
    (0.02, 0.013),
    (0.05, 0.0325),
    (0.10, 0.065),
)
SEEDS = tuple(range(20))


def _format_csv(value: object) -> object:
    if isinstance(value, (float, np.floating)):
        return f"{float(value):.9g}"
    return value


def write_csv(
    rows: Sequence[dict[str, object]],
    csv_path: Path,
    *,
    lineterminator: str = "\n",
) -> None:
    if not rows:
        raise ValueError(f"Cannot write an empty table: {csv_path}")
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    fields = list(rows[0])
    with csv_path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=fields, lineterminator=lineterminator)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: _format_csv(row[key]) for key in fields})


def write_table(rows: Sequence[dict[str, object]], csv_path: Path) -> None:
    # Preserve the legacy raw-table CSV format used by smoke and practical bounds.
    write_csv(rows, csv_path, lineterminator="\r\n")
    write_latex(rows, csv_path.with_suffix(".tex"))


def _latex_escape(value: object) -> str:
    text = _format_csv(value)
    return str(text).replace("_", r"\_").replace("%", r"\%")


def write_latex(rows: Sequence[dict[str, object]], tex_path: Path) -> None:
    fields = list(rows[0])
    alignment = "l" + "r" * (len(fields) - 1)
    lines = [
        "% Auto-generated by scripts/revision/run_studies.py",
        rf"\begin{{tabular}}{{{alignment}}}",
        r"\toprule",
        " & ".join(_latex_escape(field) for field in fields) + r" \\",
        r"\midrule",
    ]
    lines.extend(" & ".join(_latex_escape(row[field]) for field in fields) + r" \\" for row in rows)
    lines.extend((r"\bottomrule", r"\end{tabular}", ""))
    tex_path.write_text("\n".join(lines), encoding="utf-8")


def _sig(value: object) -> str:
    return f"{float(value):.3g}"


# Manuscript display precision, matched to the real-robot tables:
# violation 1 decimal, errors 2 decimals, travel time 1 decimal.
_METRIC_DECIMALS = {
    "violation_ratio": 1,
    "mean_error": 2,
    "max_error": 2,
    "travel_time": 1,
    "max_abs_curvature": 1,
}


def _dec(value: object, places: int) -> str:
    return f"{float(value):.{places}f}"


def _param(value: object) -> str:
    """Swept-parameter display: significant digits, but never bare integers."""
    text = _sig(value)
    return text if "." in text else f"{text}.0"


def _latex_display(value: object) -> str:
    # Spaced "a +- b" renders as "a $\pm$ b"; tight "a+-b" (used by the
    # compact per-controller tables) renders as "a$\pm$b".
    return _latex_escape(value).replace(" +- ", r" $\pm$ ").replace("+-", r"$\pm$")


def _write_manuscript_latex(
    tex_path: Path,
    *,
    caption: str,
    alignment: str,
    header_lines: Sequence[str],
    body_rows: Sequence[Sequence[object]],
) -> None:
    lines = [
        "% Auto-generated by scripts/revision/run_studies.py",
        r"\begin{table}[t]",
        r"\centering",
        rf"\caption{{{caption}}}",
        rf"\begin{{tabular}}{{{alignment}}}",
        r"\toprule",
        *header_lines,
        r"\midrule",
    ]
    lines.extend(" & ".join(_latex_display(value) for value in row) + r" \\" for row in body_rows)
    lines.extend((r"\bottomrule", r"\end{tabular}", r"\end{table}", ""))
    tex_path.write_text("\n".join(lines), encoding="utf-8")


def _write_app_table(rows: Sequence[dict[str, object]], out: Path) -> None:
    table_rows: list[dict[str, object]] = []
    for value in sorted({float(row["lookahead_time"]) for row in rows}):
        app = _filter(rows, arm="APP", lookahead_time=value)[0]
        dynamic = _filter(rows, arm="APP+DW", lookahead_time=value)[0]
        table_rows.append(
            {
                "l_t [s]": _dec(value, 1),
                "APP Violation [%]": _dec(app["violation_ratio"], 1),
                "APP Mean err. [m]": _dec(app["mean_error"], 2),
                "APP Max err. [m]": _dec(app["max_error"], 2),
                "APP Time [s]": _dec(app["travel_time"], 1),
                "APP+DW Violation [%]": _dec(dynamic["violation_ratio"], 1),
                "APP+DW Mean err. [m]": _dec(dynamic["mean_error"], 2),
                "APP+DW Max err. [m]": _dec(dynamic["max_error"], 2),
                "APP+DW Time [s]": _dec(dynamic["travel_time"], 1),
            }
        )
    write_csv(table_rows, out / "app_table.csv")
    _write_manuscript_latex(
        out / "app_table.tex",
        caption=r"PathC adaptive-lookahead results.",
        alignment="rrrrrrrrr",
        header_lines=(
            r" & \multicolumn{4}{c}{APP} & \multicolumn{4}{c}{APP+DW} \\",
            r"\cmidrule(lr){2-5}\cmidrule(lr){6-9}",
            r"$l_t$ [s] & Violation [\%] & Mean err. [m] & Max err. [m] & Time [s] & Violation [\%] & Mean err. [m] & Max err. [m] & Time [s] \\",
        ),
        body_rows=[tuple(row.values()) for row in table_rows],
    )
    # Per-arm fragments for the side-by-side subtable layout of the manuscript.
    for arm, stem in (("APP", "app"), ("APP+DW", "appdw")):
        arm_rows = []
        for value in sorted({float(row["lookahead_time"]) for row in rows}):
            row = _filter(rows, arm=arm, lookahead_time=value)[0]
            arm_rows.append(
                {
                    "l_t [s]": _dec(value, 1),
                    "Violation [%]": _dec(row["violation_ratio"], 1),
                    "Mean err. [m]": _dec(row["mean_error"], 2),
                    "Max err. [m]": _dec(row["max_error"], 2),
                    "Time [s]": _dec(row["travel_time"], 1),
                }
            )
        write_csv(arm_rows, out / f"app_table_{stem}.csv")
        _write_manuscript_latex(
            out / f"app_table_{stem}.tex",
            caption=f"PathC adaptive-lookahead results ({arm}).",
            alignment="rrrrr",
            header_lines=(
                r"$l_t$ [s] & Viol. [\%] & Mean [m] & Max [m] & Time [s] \\",
            ),
            body_rows=[tuple(row.values()) for row in arm_rows],
        )


def _write_rpp_table(rows: Sequence[dict[str, object]], out: Path) -> None:
    table_rows: list[dict[str, object]] = []
    for value in sorted({float(row["regulated_min_radius"]) for row in rows}):
        rpp = _filter(rows, arm="RPP", regulated_min_radius=value)[0]
        dwpp = _filter(rows, arm="DWPP", regulated_min_radius=value)[0]
        table_rows.append(
            {
                "R_min [m]": _param(value),
                "RPP Violation [%]": _dec(rpp["violation_ratio"], 1),
                "RPP Mean err. [m]": _dec(rpp["mean_error"], 2),
                "RPP Max err. [m]": _dec(rpp["max_error"], 2),
                "RPP Time [s]": _dec(rpp["travel_time"], 1),
                "DWPP Violation [%]": _dec(dwpp["violation_ratio"], 1),
                "DWPP Mean err. [m]": _dec(dwpp["mean_error"], 2),
                "DWPP Max err. [m]": _dec(dwpp["max_error"], 2),
                "DWPP Time [s]": _dec(dwpp["travel_time"], 1),
            }
        )
    write_csv(table_rows, out / "rpp_table.csv")
    _write_manuscript_latex(
        out / "rpp_table.tex",
        caption=r"PathC curvature-regulation results.",
        alignment="rrrrrrrrr",
        header_lines=(
            r" & \multicolumn{4}{c}{RPP} & \multicolumn{4}{c}{RPP+DW} \\",
            r"\cmidrule(lr){2-5}\cmidrule(lr){6-9}",
            r"$R_{min}$ [m] & Violation [\%] & Mean err. [m] & Max err. [m] & Time [s] & Violation [\%] & Mean err. [m] & Max err. [m] & Time [s] \\",
        ),
        body_rows=[tuple(row.values()) for row in table_rows],
    )
    # Per-arm fragments for the side-by-side subtable layout of the manuscript.
    for arm, stem in (("RPP", "rpp"), ("DWPP", "dwpp")):
        arm_rows = []
        for value in sorted({float(row["regulated_min_radius"]) for row in rows}):
            row = _filter(rows, arm=arm, regulated_min_radius=value)[0]
            arm_rows.append(
                {
                    "R_min [m]": _param(value),
                    "Violation [%]": _dec(row["violation_ratio"], 1),
                    "Mean err. [m]": _dec(row["mean_error"], 2),
                    "Max err. [m]": _dec(row["max_error"], 2),
                    "Time [s]": _dec(row["travel_time"], 1),
                }
            )
        write_csv(arm_rows, out / f"rpp_table_{stem}.csv")
        _write_manuscript_latex(
            out / f"rpp_table_{stem}.tex",
            caption=f"PathC curvature-regulation results ({arm}).",
            alignment="rrrrr",
            header_lines=(
                r"$R_{\min}$ [m] & Viol. [\%] & Mean [m] & Max [m] & Time [s] \\",
            ),
            body_rows=[tuple(row.values()) for row in arm_rows],
        )


def _mean_std_cell(row: dict[str, object], metric: str, *, noisy: bool) -> str:
    places = _METRIC_DECIMALS[metric]
    mean = _dec(row[f"{metric}_mean"], places)
    if not noisy:
        return mean
    return f"{mean} +- {_dec(row[f'{metric}_std'], places)}"


def _tight_mean_std_cell(row: dict[str, object], metric: str, *, noisy: bool) -> str:
    """Compact ``mean+-sd`` cell (no surrounding spaces) for narrow subtables."""
    places = _METRIC_DECIMALS[metric]
    mean = _dec(row[f"{metric}_mean"], places)
    if not noisy:
        return mean
    return f"{mean}+-{_dec(row[f'{metric}_std'], places)}"


def _reach_cell(row: dict[str, object]) -> str:
    """Yes/No goal-reaching cell, with a k/n fallback for partial reaching."""
    count = int(row["reached_goal_count"])
    total = int(row["n"])
    if count == total:
        return "Yes"
    if count == 0:
        return "No"
    return f"{count}/{total}"


def _time_cell(row: dict[str, object], *, noisy: bool) -> str:
    """Travel time cell; timed-out settings (no seed reached) show a dash."""
    if int(row["reached_goal_count"]) == 0:
        return "--"
    return _mean_std_cell(row, "travel_time", noisy=noisy)


def _write_noise_table(rows: Sequence[dict[str, object]], out: Path) -> None:
    table_rows: list[dict[str, object]] = []
    for row in rows:
        noisy = float(row["sigma_xy"]) > 0.0
        table_rows.append(
            {
                "sigma_xy [m]": _sig(row["sigma_xy"]),
                "Controller": row["controller"],
                "Violation [%]": _mean_std_cell(row, "violation_ratio", noisy=noisy),
                "Mean err. [m]": _mean_std_cell(row, "mean_error", noisy=noisy),
                "Max err. [m]": _mean_std_cell(row, "max_error", noisy=noisy),
                "Time [s]": _time_cell(row, noisy=noisy),
                "Reach": _reach_cell(row),
            }
        )
    write_csv(table_rows, out / "noise_table.csv")
    _write_manuscript_latex(
        out / "noise_table.tex",
        caption=r"PathC localization-noise results. Nonzero-noise metrics are mean $\pm$ standard deviation over 20 seeds; -- marks settings that never reached the goal within the 120 s timeout.",
        alignment="rlrrrrr",
        header_lines=(
            r"$\sigma_{xy}$ [m] & Controller & Violation [\%] & Mean err. [m] & Max err. [m] & Time [s] & Reach \\",
        ),
        body_rows=[tuple(row.values()) for row in table_rows],
    )
    # Per-controller fragments for the 2x2 subtable layout of the manuscript.
    for controller in CONTROLLERS:
        sub_rows = []
        for row in _filter(rows, controller=controller):
            noisy = float(row["sigma_xy"]) > 0.0
            sub_rows.append(
                {
                    "sigma_xy [m]": _sig(row["sigma_xy"]),
                    "Violation [%]": _tight_mean_std_cell(row, "violation_ratio", noisy=noisy),
                    "Mean err. [m]": _tight_mean_std_cell(row, "mean_error", noisy=noisy),
                    "Max err. [m]": _tight_mean_std_cell(row, "max_error", noisy=noisy),
                    "Time [s]": "--" if int(row["reached_goal_count"]) == 0 else _tight_mean_std_cell(row, "travel_time", noisy=noisy),
                    "Reach": _reach_cell(row),
                }
            )
        write_csv(sub_rows, out / f"noise_table_{controller.lower()}.csv")
        _write_manuscript_latex(
            out / f"noise_table_{controller.lower()}.tex",
            caption=f"PathC localization-noise results ({controller}).",
            alignment="rrrrrr",
            header_lines=(
                r"$\sigma_{xy}$ [m] & Viol. [\%] & Mean [m] & Max [m] & Time [s] & Reach \\",
            ),
            body_rows=[tuple(row.values()) for row in sub_rows],
        )


def _write_lookahead_table(rows: Sequence[dict[str, object]], out: Path) -> None:
    table_rows: list[dict[str, object]] = []
    for value in sorted({float(row["lookahead"]) for row in rows}):
        noiseless = _filter(rows, lookahead=value, sigma_xy=0.0)[0]
        noisy = _filter(rows, lookahead=value, sigma_xy=0.05)[0]
        table_rows.append(
            {
                "L [m]": _dec(value, 1),
                "sigma=0 Mean err. [m]": _dec(noiseless["mean_error_mean"], 2),
                "sigma=0 Max err. [m]": _dec(noiseless["max_error_mean"], 2),
                "sigma=0 Time [s]": _dec(noiseless["travel_time_mean"], 1),
                "sigma=0.05 Mean err. [m]": _tight_mean_std_cell(noisy, "mean_error", noisy=True),
                "sigma=0.05 Max err. [m]": _tight_mean_std_cell(noisy, "max_error", noisy=True),
                "sigma=0.05 Time [s]": "--" if int(noisy["reached_goal_count"]) == 0 else _tight_mean_std_cell(noisy, "travel_time", noisy=True),
                "sigma=0.05 Reach": _reach_cell(noisy),
            }
        )
    write_csv(table_rows, out / "lookahead_table.csv")
    _write_manuscript_latex(
        out / "lookahead_table.tex",
        caption=r"PathC fixed-lookahead DWPP results. The $\sigma_{xy}=0.05$ m entries are mean $\pm$ standard deviation over 20 seeds; the violation ratio was 0\% for every setting; -- marks settings that never reached the goal within the 120 s timeout.",
        alignment="rrrrrrrr",
        header_lines=(
            r" & \multicolumn{3}{c}{$\sigma_{xy}=0$ m} & \multicolumn{4}{c}{$\sigma_{xy}=0.05$ m} \\",
            r"\cmidrule(lr){2-4}\cmidrule(lr){5-8}",
            r"$L$ [m] & Mean err. [m] & Max err. [m] & Time [s] & Mean err. [m] & Max err. [m] & Time [s] & Reach \\",
        ),
        body_rows=[tuple(row.values()) for row in table_rows],
    )
    # Per-noise-level fragments for the side-by-side subtable layout.
    noiseless_rows = [
        {
            "L [m]": row["L [m]"],
            "Mean err. [m]": row["sigma=0 Mean err. [m]"],
            "Max err. [m]": row["sigma=0 Max err. [m]"],
            "Time [s]": row["sigma=0 Time [s]"],
        }
        for row in table_rows
    ]
    noisy_rows = [
        {
            "L [m]": row["L [m]"],
            "Mean err. [m]": row["sigma=0.05 Mean err. [m]"],
            "Max err. [m]": row["sigma=0.05 Max err. [m]"],
            "Time [s]": row["sigma=0.05 Time [s]"],
            "Reach": row["sigma=0.05 Reach"],
        }
        for row in table_rows
    ]
    write_csv(noiseless_rows, out / "lookahead_table_noiseless.csv")
    _write_manuscript_latex(
        out / "lookahead_table_noiseless.tex",
        caption=r"PathC fixed-lookahead DWPP results ($\sigma_{xy}=0$ m).",
        alignment="rrrr",
        header_lines=(r"$L$ [m] & Mean [m] & Max [m] & Time [s] \\",),
        body_rows=[tuple(row.values()) for row in noiseless_rows],
    )
    write_csv(noisy_rows, out / "lookahead_table_noisy.csv")
    _write_manuscript_latex(
        out / "lookahead_table_noisy.tex",
        caption=r"PathC fixed-lookahead DWPP results ($\sigma_{xy}=0.05$ m).",
        alignment="rrrrr",
        header_lines=(r"$L$ [m] & Mean [m] & Max [m] & Time [s] & Reach \\",),
        body_rows=[tuple(row.values()) for row in noisy_rows],
    )


def _write_isotime_table(rows: Sequence[dict[str, object]], out: Path) -> None:
    table_rows = [
        {
            "Controller": row["controller"],
            "v_max [m/s]": _dec(row["v_max"], 3),
            "R_min [m]": "--" if row["r_min"] is None else _param(row["r_min"]),
            "Time [s]": _dec(row["travel_time"], 1),
            "Mean err. [m]": _dec(row["mean_error"], 2),
            "Max err. [m]": _dec(row["max_error"], 2),
            "Violation [%]": _dec(row["violation_ratio"], 1),
        }
        for row in rows
    ]
    write_csv(table_rows, out / "isotime_table.csv")
    _write_manuscript_latex(
        out / "isotime_table.tex",
        caption=r"PathC matched-travel-time comparison (single noiseless runs).",
        alignment="lrrrrrr",
        header_lines=(
            r"Controller & $v_{\max}$ [m/s] & $R_{\min}$ [m] & Time [s] & Mean err. [m] & Max err. [m] & Violation [\%] \\",
        ),
        body_rows=[tuple(row.values()) for row in table_rows],
    )


def _run(
    path: np.ndarray,
    path_name: str,
    config: SimulationConfig,
    *,
    sigma_xy: float = 0.0,
    sigma_yaw: float = 0.0,
    seed: int = 0,
) -> TrialResult:
    return simulate_trial(
        path,
        path_name,
        config,
        sigma_xy=sigma_xy,
        sigma_yaw=sigma_yaw,
        seed=seed,
    )


def run_smoke(output_root: Path = DEFAULT_OUTPUT_ROOT) -> dict[str, object]:
    paths = make_paths()
    rows: list[dict[str, object]] = []
    results: dict[tuple[str, str], TrialResult] = {}
    for path_name, path in paths.items():
        for controller in CONTROLLERS:
            result = _run(path, path_name, controller_config(controller))
            results[path_name, controller] = result
            rows.append(result.as_row())
    out = output_root / "smoke"
    write_table(rows, out / "smoke_table.csv")

    path_c = [results["PathC", name].mean_error for name in CONTROLLERS]
    ordering_pass = all(left > right for left, right in zip(path_c, path_c[1:]))
    zero_pass = all(results[path_name, "DWPP"].violation_ratio == 0.0 for path_name in paths)
    goal_pass = all(result.reached_goal for result in results.values())
    passed = ordering_pass and zero_pass and goal_pass
    ordering = {
        path_name: " > ".join(
            name for name, _ in sorted(
                ((controller, results[path_name, controller].mean_error) for controller in CONTROLLERS),
                key=lambda item: item[1],
                reverse=True,
            )
        )
        for path_name in paths
    }
    print(
        f"SMOKE {'PASS' if passed else 'FAIL'}: PathC={ordering['PathC']}; "
        f"DWPP zero violation={zero_pass}; all reached={goal_pass}"
    )
    if not passed:
        details = ", ".join(f"{name}={results['PathC', name].mean_error:.6f}" for name in CONTROLLERS)
        raise AssertionError(
            f"Smoke requirements failed ({details}; DWPP zero violation={zero_pass}; all reached={goal_pass})"
        )
    return {"passed": passed, "ordering": ordering, "rows": rows}


def _study_rows(
    values: Iterable[float],
    paths: dict[str, np.ndarray],
    arms: Sequence[str],
    config_builder: Callable[[str, float], SimulationConfig],
    parameter_name: str,
    result_store: dict[tuple[str, str, float], TrialResult] | None = None,
) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for path_name, path in paths.items():
        for value in values:
            for arm in arms:
                result = _run(path, path_name, config_builder(arm, float(value)))
                if result_store is not None:
                    result_store[path_name, arm, float(value)] = result
                row = result.as_row()
                row = {"path": row.pop("path"), "arm": arm, parameter_name: float(value), **row}
                rows.append(row)
    return rows


def _filter(rows: Sequence[dict[str, object]], **conditions: object) -> list[dict[str, object]]:
    return [row for row in rows if all(row[key] == value for key, value in conditions.items())]


def run_app(output_root: Path = DEFAULT_OUTPUT_ROOT) -> dict[str, object]:
    values = np.round(np.linspace(0.6, 3.0, 13), 10)
    path = make_paths()["PathC"]
    paths = {"PathC": path}

    def build(arm: str, value: float) -> SimulationConfig:
        base = controller_config("APP")
        # 本スタディのみ上側クランプを緩和 (0.5 m/s x 3.0 s = 1.5 m < 2.0 m で
        # スイープ全域が非飽和になり、velocity-scaled lookahead の効果を分離できる)。
        # 下側クランプ 0.3 m は安定性の床として凍結値を維持。
        return replace(
            base,
            controller_name=arm,
            lookahead_time=value,
            max_lookahead=2.0,
            use_dynamic_window=arm == "APP+DW",
            use_curvature_regulation=False,
        )

    trial_results: dict[tuple[str, str, float], TrialResult] = {}
    rows = _study_rows(
        values,
        paths,
        ("APP", "APP+DW"),
        build,
        "lookahead_time",
        trial_results,
    )
    out = output_root / "app"
    _write_app_table(rows, out)
    path_c_groups = []
    violation_groups = []
    for arm in ("APP", "APP+DW"):
        selected = _filter(rows, path="PathC", arm=arm)
        path_c_groups.append(
            (
                arm,
                [float(row["lookahead_time"]) for row in selected],
                [float(row["mean_error"]) for row in selected],
                [float(row["travel_time"]) for row in selected],
            )
        )
        violation_groups.append(
            (
                arm,
                [float(row["lookahead_time"]) for row in selected],
                [float(row["violation_ratio"]) for row in selected],
            )
        )
    plot_lookahead_tradeoff(
        path_c_groups,
        out / "app_tradeoff",
        title="PathC: adaptive-lookahead trade-off",
        xlabel=r"Lookahead time gain $l_t$ [s]",
        colors=[COLORS["APP"], COLORS["APP+DW"]],
    )
    plot_lines(
        violation_groups,
        out / "app_violation_vs_lookahead_time",
        xlabel=r"Lookahead time $l_t$ [s]",
        ylabel="Constraint violation ratio [%]",
        title="PathC: dynamic-constraint violations",
    )
    trajectory_values = (0.6, 1.4, 2.2, 3.0)

    def arm_panel(arm: str) -> list[tuple[str, list[tuple[str, np.ndarray]]]]:
        # Empty panel title: the manuscript names the arms in subcaptions.
        return [
            (
                "",
                [
                    (
                        rf"$l_t={value:g}$ s",
                        trial_results["PathC", arm, value].positions,
                    )
                    for value in trajectory_values
                ],
            )
        ]

    # Draw APP+DW first and reuse its plotting range for APP so the two
    # panels are directly comparable (the APP oscillation may leave the frame).
    dw_xlim, dw_ylim = plot_trajectories(
        path,
        arm_panel("APP+DW"),
        out / "app_trajectories_appdw",
        figsize=(3.4, 3.4),
        legend=False,
    )
    plot_trajectories(
        path,
        arm_panel("APP"),
        out / "app_trajectories_app",
        xlim=dw_xlim,
        ylim=dw_ylim,
        figsize=(3.4, 3.4),
        legend=False,
    )
    save_trajectory_legend(
        [rf"$l_t={value:g}$ s" for value in trajectory_values],
        out / "app_trajectories_legend",
    )
    comparisons = []
    for path_name in paths:
        for value in values:
            plain = _filter(rows, path=path_name, arm="APP", lookahead_time=float(value))[0]
            dynamic = _filter(rows, path=path_name, arm="APP+DW", lookahead_time=float(value))[0]
            comparisons.append(float(dynamic["mean_error"]) - float(plain["mean_error"]))
    app_dw_zero = all(
        float(row["violation_ratio"]) == 0.0 for row in _filter(rows, arm="APP+DW")
    )
    if not app_dw_zero:
        raise AssertionError("APP+DW produced a constraint violation in the APP study")
    return {
        "rows": rows,
        "app_dw_exceeds_count": int(sum(delta > 1e-12 for delta in comparisons)),
        "max_app_dw_minus_app": max(comparisons),
        "app_dw_zero_violation": app_dw_zero,
    }


def run_rpp(output_root: Path = DEFAULT_OUTPUT_ROOT) -> dict[str, object]:
    values = np.round(np.linspace(0.2, 2.0, 10), 10)
    path = make_paths()["PathC"]
    paths = {"PathC": path}

    def build(arm: str, value: float) -> SimulationConfig:
        base = controller_config(arm)
        return replace(base, regulated_min_radius=value)

    trial_results: dict[tuple[str, str, float], TrialResult] = {}
    rows = _study_rows(
        values,
        paths,
        ("RPP", "DWPP"),
        build,
        "regulated_min_radius",
        trial_results,
    )
    out = output_root / "rpp"
    _write_rpp_table(rows, out)
    tradeoff_groups = []
    violation_groups = []
    for arm in ("RPP", "DWPP"):
        selected = _filter(rows, path="PathC", arm=arm)
        # Manuscript ablation naming: the DW arm is displayed as RPP+DW.
        display = "RPP+DW" if arm == "DWPP" else arm
        tradeoff_groups.append(
            (
                display,
                [float(row["regulated_min_radius"]) for row in selected],
                [float(row["mean_error"]) for row in selected],
                [float(row["travel_time"]) for row in selected],
            )
        )
        violation_groups.append(
            (
                arm,
                [float(row["regulated_min_radius"]) for row in selected],
                [float(row["violation_ratio"]) for row in selected],
            )
        )
    plot_lookahead_tradeoff(
        tradeoff_groups,
        out / "rpp_tradeoff",
        title="PathC: curvature-regulation trade-off",
        xlabel=r"Regulated minimum radius $R_{\min}$ [m]",
        colors=[COLORS["RPP"], COLORS["DWPP"]],
    )
    plot_lines(
        violation_groups,
        out / "rpp_violation_vs_min_radius",
        xlabel=r"Minimum radius $R_{min}$ [m]",
        ylabel="Constraint violation ratio [%]",
        title="PathC: dynamic-constraint violations",
    )
    trajectory_values = (0.2, 0.8, 1.4, 2.0)

    def arm_panel(arm: str) -> list[tuple[str, list[tuple[str, np.ndarray]]]]:
        # Empty panel title: the manuscript names the arms in subcaptions.
        return [
            (
                "",
                [
                    (
                        rf"$R_{{min}}={value:g}$ m",
                        trial_results["PathC", arm, value].positions,
                    )
                    for value in trajectory_values
                ],
            )
        ]

    # Draw DWPP first and reuse its plotting range for RPP so the two
    # panels are directly comparable.
    dwpp_xlim, dwpp_ylim = plot_trajectories(
        path,
        arm_panel("DWPP"),
        out / "rpp_trajectories_dwpp",
        figsize=(3.4, 3.4),
        legend=False,
    )
    plot_trajectories(
        path,
        arm_panel("RPP"),
        out / "rpp_trajectories_rpp",
        xlim=dwpp_xlim,
        ylim=dwpp_ylim,
        figsize=(3.4, 3.4),
        legend=False,
    )
    save_trajectory_legend(
        [rf"$R_{{min}}={value:g}$ m" for value in trajectory_values],
        out / "rpp_trajectories_legend",
    )
    summary: dict[str, object] = {"rows": rows}
    for arm in ("RPP", "DWPP"):
        selected = _filter(rows, path="PathC", arm=arm)
        summary[f"{arm.lower()}_error_endpoints"] = (
            float(selected[0]["mean_error"]),
            float(selected[-1]["mean_error"]),
        )
        summary[f"{arm.lower()}_time_endpoints"] = (
            float(selected[0]["travel_time"]),
            float(selected[-1]["travel_time"]),
        )
    dwpp_zero = all(float(row["violation_ratio"]) == 0.0 for row in _filter(rows, arm="DWPP"))
    if not dwpp_zero:
        raise AssertionError("DWPP produced a constraint violation in the RPP study")
    summary["dwpp_zero_violation"] = dwpp_zero
    return summary


def _aggregate_trials(
    trials: Sequence[TrialResult],
    identifying: dict[str, object],
) -> dict[str, object]:
    row: dict[str, object] = {**identifying, "n": len(trials)}
    row["reached_goal_count"] = sum(trial.reached_goal for trial in trials)
    row["reached_goal_rate"] = 100.0 * float(row["reached_goal_count"]) / len(trials)
    for metric in ("travel_time", "mean_error", "max_error", "violation_ratio", "max_abs_curvature"):
        values = np.asarray([getattr(trial, metric) for trial in trials], dtype=float)
        row[f"{metric}_mean"] = float(np.mean(values))
        row[f"{metric}_std"] = float(np.std(values, ddof=1)) if len(values) > 1 else 0.0
    return row


def run_noise(output_root: Path = DEFAULT_OUTPUT_ROOT) -> dict[str, object]:
    path = make_paths()["PathC"]
    rows: list[dict[str, object]] = []
    trajectory_results: dict[str, TrialResult] = {}
    profile_results: dict[str, TrialResult] = {}
    for sigma_xy, sigma_yaw in NOISE_LEVELS:
        for controller in CONTROLLERS:
            trials = [
                _run(
                    path,
                    "PathC",
                    controller_config(controller),
                    sigma_xy=sigma_xy,
                    sigma_yaw=sigma_yaw,
                    seed=seed,
                )
                for seed in SEEDS
            ]
            if sigma_xy == 0.02:
                trajectory_results[controller] = trials[0]
            if sigma_xy == 0.05:
                profile_results[controller] = trials[0]
            rows.append(
                _aggregate_trials(
                    trials,
                    {"path": "PathC", "controller": controller, "sigma_xy": sigma_xy, "sigma_yaw": sigma_yaw},
                )
            )
    out = output_root / "noise"
    _write_noise_table(rows, out)
    error_groups = []
    violation_groups = []
    for controller in CONTROLLERS:
        selected = _filter(rows, controller=controller)
        xs = [float(row["sigma_xy"]) for row in selected]
        error_groups.append(
            (
                controller,
                xs,
                [float(row["mean_error_mean"]) for row in selected],
                [float(row["mean_error_std"]) for row in selected],
            )
        )
        violation_groups.append(
            (
                controller,
                xs,
                [float(row["violation_ratio_mean"]) for row in selected],
                [float(row["violation_ratio_std"]) for row in selected],
            )
        )
    plot_bands(
        error_groups,
        out / "noise_mean_error",
        xlabel=r"Position-noise standard deviation $\sigma_{xy}$ [m]",
        ylabel="Mean tracking error [m]",
        title="PathC: localization-noise sensitivity",
    )
    plot_bands(
        violation_groups,
        out / "noise_violation_ratio",
        xlabel=r"Position-noise standard deviation $\sigma_{xy}$ [m]",
        ylabel="Constraint violation ratio [%]",
        title="PathC: violations under localization noise",
    )
    plot_trajectories(
        path,
        [
            (
                r"$\sigma_{xy}=0.02$ m, seed 0",
                [
                    (controller, trajectory_results[controller].positions)
                    for controller in CONTROLLERS
                ],
            )
        ],
        out / "noise_trajectories",
    )
    plot_velocity_profiles(
        [
            (
                controller,
                DEFAULT_CONFIG.dt,
                profile_results[controller].commands,
                profile_results[controller].applied_commands,
            )
            for controller in CONTROLLERS
        ],
        out / "noise_velocity_profile",
        v_max=DEFAULT_CONFIG.max_linear_velocity,
        w_max=DEFAULT_CONFIG.max_angular_velocity,
    )
    dwpp_zero = all(float(row["violation_ratio_mean"]) == 0.0 for row in _filter(rows, controller="DWPP"))
    if not dwpp_zero:
        raise AssertionError("DWPP produced a constraint violation in the noise study")
    return {"rows": rows, "dwpp_zero_violation": dwpp_zero}


def run_lookahead(output_root: Path = DEFAULT_OUTPUT_ROOT) -> dict[str, object]:
    path = make_paths()["PathC"]
    values = np.round(np.arange(0.2, 1.21, 0.1), 10)
    # Noise OFF/ON only: the noiseless baseline and the severe level of the
    # noise study (sigma_yaw = 0.65 * sigma_xy, as in NOISE_LEVELS).
    noise_levels = ((0.0, 0.0), (0.05, 0.0325))
    rows: list[dict[str, object]] = []
    trajectory_results: dict[float, TrialResult] = {}
    for sigma_xy, sigma_yaw in noise_levels:
        seeds = (0,) if sigma_xy == 0.0 else SEEDS
        for lookahead in values:
            config = replace(
                controller_config("DWPP"),
                use_velocity_scaled_lookahead=False,
                fixed_lookahead=float(lookahead),
            )
            trials = [
                _run(
                    path,
                    "PathC",
                    config,
                    sigma_xy=sigma_xy,
                    sigma_yaw=sigma_yaw,
                    seed=seed,
                )
                for seed in seeds
            ]
            if sigma_xy == 0.0:
                trajectory_results[float(lookahead)] = trials[0]
            rows.append(
                _aggregate_trials(
                    trials,
                    {"path": "PathC", "lookahead": float(lookahead), "sigma_xy": sigma_xy, "sigma_yaw": sigma_yaw},
                )
            )
    out = output_root / "lookahead"
    _write_lookahead_table(rows, out)
    tradeoff_groups = []
    practical_bounds: dict[float, float] = {}
    summary_rows: list[dict[str, object]] = []
    for sigma_xy, _ in noise_levels:
        selected = _filter(rows, sigma_xy=sigma_xy)
        label = rf"$\sigma_{{xy}}={sigma_xy:g}$ m"
        xs = [float(row["lookahead"]) for row in selected]
        means = [float(row["mean_error_mean"]) for row in selected]
        completed = [
            (x, mean)
            for x, mean, row in zip(xs, means, selected, strict=True)
            if int(row["reached_goal_count"]) == int(row["n"])
        ]
        if not completed:
            raise RuntimeError(f"No lookahead completed every trial at sigma_xy={sigma_xy}")
        threshold = min(mean for _, mean in completed) * 1.10
        usable = [x for x, mean in completed if mean <= threshold]
        practical_bounds[sigma_xy] = min(usable)
        summary_rows.append(
            {
                "sigma_xy": sigma_xy,
                "practical_lower_bound": min(usable),
                "criterion": "100% goal; error <= 1.10 * successful minimum",
                "minimum_mean_error": min(mean for _, mean in completed),
            }
        )
        fully_successful = [
            row for row in selected if float(row["reached_goal_rate"]) == 100.0
        ]
        tradeoff_groups.append(
            (
                label,
                [float(row["lookahead"]) for row in fully_successful],
                [float(row["mean_error_mean"]) for row in fully_successful],
                [float(row["travel_time_mean"]) for row in fully_successful],
            )
        )
    write_table(summary_rows, out / "lookahead_practical_bounds.csv")
    plot_lookahead_tradeoff(
        tradeoff_groups,
        out / "lookahead_tradeoff",
        title="PathC: fixed-lookahead trade-off",
    )
    plot_trajectories(
        path,
        [
            (
                "DWPP",
                [
                    (rf"$L={value:g}$ m", trajectory_results[value].positions)
                    for value in (0.3, 0.6, 0.9, 1.2)
                ],
            )
        ],
        out / "lookahead_trajectories",
        linewidth=1.8,
        font_size=17,
    )
    dwpp_zero = all(float(row["violation_ratio_mean"]) == 0.0 for row in rows)
    if not dwpp_zero:
        raise AssertionError("DWPP produced a constraint violation in the lookahead study")
    return {
        "rows": rows,
        "practical_lower_bounds": practical_bounds,
        "dwpp_zero_violation": dwpp_zero,
    }


def _match_time(
    path: np.ndarray,
    path_name: str,
    controller: str,
    target_time: float,
) -> TrialResult:
    low = 0.05
    high = DEFAULT_CONFIG.max_linear_velocity
    best: TrialResult | None = None
    # Full bisection without an early stop: the travel time is quantized by the
    # control period, so running all iterations and keeping the closest visited
    # result matches the target down to roughly one control step.
    for _ in range(28):
        value = (low + high) / 2.0
        config = replace(controller_config(controller), max_linear_velocity=value)
        result = _run(path, path_name, config)
        if best is None or abs(result.travel_time - target_time) < abs(best.travel_time - target_time):
            best = result
        if result.travel_time > target_time:
            low = value
        else:
            high = value
    assert best is not None
    if abs(best.travel_time - target_time) / target_time > 0.02:
        raise RuntimeError(
            f"Could not match {path_name}/{controller} to {target_time:.3f}s; best={best.travel_time:.3f}s"
        )
    return best


def run_isotime(output_root: Path = DEFAULT_OUTPUT_ROOT) -> dict[str, object]:
    rows: list[dict[str, object]] = []
    path_name = "PathC"
    path = make_paths()[path_name]
    # Matched conditions drawn from the R_min sweep of the rpp study: RPP is
    # slowest at the largest swept threshold, and DWPP at R_min = 0.4 has the
    # closest travel time (identical to R_min = 0.2, where the regulation is
    # inactive because the window projection caps the corner speed below the
    # regulation floor). PP and APP are then bisected to the DWPP travel time.
    rpp = _run(path, path_name, replace(controller_config("RPP"), regulated_min_radius=2.0))
    dwpp = _run(path, path_name, replace(controller_config("DWPP"), regulated_min_radius=0.4))
    trajectory_results: dict[str, TrialResult] = {}
    for controller in ("PP", "APP"):
        result = _match_time(path, path_name, controller, dwpp.travel_time)
        trajectory_results[f"{controller}@matched"] = result
        rows.append(
            {
                "controller": controller,
                "v_max": float(np.max(result.commands[:, 0])),
                "r_min": None,
                "travel_time": result.travel_time,
                "mean_error": result.mean_error,
                "max_error": result.max_error,
                "violation_ratio": result.violation_ratio,
            }
        )
    for label, result, r_min in (("RPP", rpp, 2.0), ("DWPP", dwpp, 0.4)):
        trajectory_results[f"{label}@matched"] = result
        rows.append(
            {
                "controller": label,
                "v_max": DEFAULT_CONFIG.max_linear_velocity,
                "r_min": r_min,
                "travel_time": result.travel_time,
                "mean_error": result.mean_error,
                "max_error": result.max_error,
                "violation_ratio": result.violation_ratio,
            }
        )
    out = output_root / "isotime"
    _write_isotime_table(rows, out)
    plot_trajectories(
        path,
        [
            (
                "PathC",
                [
                    (label, trajectory_results[label].positions)
                    for label in ("PP@matched", "APP@matched", "RPP@matched", "DWPP@matched")
                ],
            )
        ],
        out / "isotime_trajectories",
    )
    return {"rows": rows}


STUDY_FUNCTIONS = {
    "smoke": run_smoke,
    "app": run_app,
    "rpp": run_rpp,
    "noise": run_noise,
    "lookahead": run_lookahead,
    "isotime": run_isotime,
}


def run_studies(study: str, output_root: Path = DEFAULT_OUTPUT_ROOT) -> dict[str, dict[str, object]]:
    names = tuple(STUDY_FUNCTIONS) if study == "all" else (study,)
    summaries: dict[str, dict[str, object]] = {}
    for index, name in enumerate(names, start=1):
        print(f"[{index}/{len(names)}] Running {name} study")
        summaries[name] = STUDY_FUNCTIONS[name](output_root)
        print(f"[{index}/{len(names)}] Completed {name} study")
    return summaries
