[project]
name = "dwp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.9.2",
    "numpy>=2.1.3",
    "pip>=24.3.1",
    "scipy>=1.15.1",
]
